/******************************************************************************
*
*  Copyright (C) 2000 Synchem Group at SUNY-Stony Brook, Jerry Miller
*
*  Module Name:                     EYC.C
*
*    Question-driven editor for schema values of ease, yield, and confidence.
*
*  Creation Date:
*
*    11-Aug-2000
*
*  Authors:
*
*    Gerald A. Miller
*
*  Modification History, reverse chronological
*
* Date       Author     Modification Description
*------------------------------------------------------------------------------
*
*
******************************************************************************/

#include <stdio.h>

#include <Xm/DialogS.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/PushBG.h>
#include <Xm/Form.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>

#ifdef TRUE
#undef TRUE
#endif

#ifdef FALSE
#undef FALSE
#endif

#include "synchem.h"
#include "app_resrc.h"

void EYCTxt_CB (Widget, XtPointer, XtPointer);
void EYCOpt_CB (Widget, XtPointer, XtPointer);
void EYCPB_CB (Widget, XtPointer, XtPointer);

static void (*ret_func)(int, int, int);

static int ease = 100, yield = 100, conf = 100, esel[4] = {0, 0, 0, 0}, csel[4] = {0, 0, 0, 0};

static char *eyc_directions[3] =
  {"You may enter the new starting values for ease, yield, and confidence directly by filling in the boxes below.  If you would",
   "prefer to be guided through the process with a series of questions and allow the system to suggest computed values for ease",
   "and confidence, which you may then either accept or modify, simply select the \"Stepwise Method\" button below."};

static char *eyc_questions[3] =
  {"Initial ease value (0-100):", "Initial yield value (0-100):", "Initial confidence value (0-100):"};

static char *num_buttons[3] =
  {"Exit and Save", "Stepwise Method", "Quit and Cancel"};

static char *eyc_buttons[2] =
  {"Submit and Continue", "Quit and Cancel"};

static char *ease_questions[4] =
  {"1) How many steps are there to this reaction that cannot be lumped together as in a one-pot reaction?",
   "2) Is the workup",
   "3) In the context of this installation of SYNCHEM2, how practical is this reaction in terms of conditions and equipment?",
   "4) Is the reaction"};

static char *ease_choices[4][5] =
  {{"1","2","3","4","5"},
   {"A) simple, as in filtration and crystallization?", "B) average, e.g., simple extraction and/or distillation?",
      "C) tedious or difficult?", "D) extremely tedious or difficult?", ""},
   {"A) routine", "B) somewhat impractical, but worthy of consideration", "C) very impractical", "", ""},
   {"A) reasonably safe, given normal precautions?", "B) moderately hazardous or a problem in terms of toxic fumes or by-products?",
      "C) very hazardous, e.g., potential for runaway exotherm or detonation?", "", ""}};

static char ease_answers[4][5] =
  {{'1','2','3','4','5'},
   {'A','B','C',' ','D'},
   {'A','B',' ','C',' '},
   {'A','B',' ','C',' '}};

static char *yield_question[11] =
  {"The yield stored for this schema should reflect your best estimate, based on literature, experience, or an educated guess, for",
   "the simplest molecule fitting the pattern.  It is expected that post-transform tests subsequently created for this schema will",
   "modify this initial estimate either upward or downward, based on their discovery of activating or deactivating groups, steric",
   "effects, or other variable features.",
   " ",
   "This is not a hard and fast rule, however - it is just as acceptable to begin with either an optimal or a very poor yield and",
   "adjust that value on the basis of tests if it seems more appropriate, provided there will be no confusion to future users as",
   "to your intent in doing so.  (Please add comments to the schema if you feel there may be some confusion about starting values",
   "of ease, yield, or confidence.)",
   " ",
   "Initial yield value (0-100):"};

static char *conf_questions[4][2] =
  {{"1) Is this reaction",
    ""},
   {"2) Are the tests you intend to add to this schema",
    ""},
   {"3) If this reaction were applied to every applicable molecule generated by SYNCHEM, what is the likelihood that any given",
    "   application will bring SYNCHEM closer to a solution, as opposed to \"side-tracking\" it?"},
   {"4) Are there other considerations that would temper your confidence in the ability of SYNCHEM to use this schema to generate",
    "   valid and/or elegant pathways (e.g., stereochemical constraints)?"}};

static char *conf_choices[4][5] =
  {{"A) generally known and accepted?",
      "B) reported by an author whose work is known for reproducibility (or discovered by your group to be reliable)?",
      "C) reported by a lesser-known author?", "D) relatively obscure?", "E) not generally considered a synthetic method?"},
   {"A) fairly complete, covering the vast majority of potential applications and exceptions?",
      "B) sufficient for at least a modicum of screening?", "C) minimal?", "", ""},
   {"A) almost certain", "B) probable", "C) as likely as not", "D) \"This is a protection/deprotection reaction.\"",
      "E) unlikely"},
   {"A) none", "B) minor reservations", "C) strong reservations", "", ""}};

static char conf_answers[4][5] =
  {{'A','B','C','D','E'},
   {'A','B',' ','C',' '},
   {'A','B','C','D','E'},
   {'A','B',' ','C',' '}};

static Widget formdg, numform, eform, yform, cform, eyctxt[3], ytxt;

void EYC_Form_Create (Widget top_level)
{
  XmString title, label, choice_lbl[5];
  Widget eyclbl[6], eycpb[3], elbl[4], edummy[4], emenu[4], epb[2], ylbl[11], ypb[2], clbl[4][2], cdummy[4], cmenu[4], cpb[2];
  int i, j, nlines, nchoices;
  char wname[16], eycval[3][5];

  sprintf (eycval[0], "%d", ease);
  sprintf (eycval[1], "%d", yield);
  sprintf (eycval[2], "%d", conf);

  formdg = XmCreateFormDialog (top_level, "EYCForm", NULL, 0);

  title = XmStringCreateLocalized ("Ease, Yield, Confidence");
  XtVaSetValues (formdg,
    XmNdialogStyle,     XmDIALOG_MODELESS,
    XmNlabelFontList,   SynAppR_FontList_Get (&GSynAppR),
    XmNbuttonFontList,  SynAppR_FontList_Get (&GSynAppR),
    XmNtextFontList,    SynAppR_FontList_Get (&GSynAppR),
    XmNbackground,      SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
    XmNforeground,      SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
    XmNresizePolicy,    XmRESIZE_NONE,
    XmNresizable,       True,
    XmNautoUnmanage,    False,
    XmNdialogTitle,     title,
    XmNdefaultPosition, False,
    XmNheight,          2 * AppDim_AppHeight_Get (&GAppDim) / 5,
    XmNwidth,           AppDim_AppWidth_Get (&GAppDim),
    NULL);
  XmStringFree (title);

  numform = XtVaCreateWidget ("EYCNumForm",
    xmFormWidgetClass, formdg,
    XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
    XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
    XmNtopOffset, 0,
    XmNtopAttachment, XmATTACH_FORM,
    XmNbottomOffset, 0,
    XmNbottomAttachment, XmATTACH_FORM,
    XmNleftOffset, 0,
    XmNleftAttachment, XmATTACH_FORM,
    XmNrightOffset, 0,
    XmNrightAttachment, XmATTACH_FORM,
    XmNfractionBase,    800,
    NULL);

  for (i = 0; i < 3; i++)
    {
    label = XmStringCreateLocalized (eyc_directions[i]);
    sprintf (wname, "EYCLbl%d", i);
    eyclbl[i] = XtVaCreateManagedWidget (wname,
      xmLabelWidgetClass, numform,
      XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
      XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
      XmNlabelString, label,
      XmNtopOffset, 0,
      XmNtopAttachment, i == 0 ? XmATTACH_FORM : XmATTACH_WIDGET,
      XmNtopWidget, i == 0 ? NULL : eyclbl[i - 1],
      XmNleftPosition, 10,
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);
    }

  for (i = 0; i < 3; i++)
    {
    label = XmStringCreateLocalized (eyc_questions[i]);
    sprintf (wname, "EYCLbl%d", i + 3);
    eyclbl[i + 3] = XtVaCreateManagedWidget (wname,
      xmLabelWidgetClass, numform,
      XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
      XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
      XmNlabelString, label,
      XmNtopPosition, 100 * i + 300,
      XmNtopAttachment, XmATTACH_POSITION,
      XmNleftPosition, 10,
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);

    sprintf (wname, "EYCTxt%d", i);
    eyctxt[i] = XtVaCreateManagedWidget (wname,
      xmTextFieldWidgetClass, numform,
      XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
      XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
      XmNvalue, eycval[i],
      XmNtopOffset, 0,
      XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET,
      XmNtopWidget, eyclbl[i + 3],
      XmNleftOffset, 0,
      XmNleftAttachment, XmATTACH_WIDGET,
      XmNleftWidget, eyclbl[i + 3],
      NULL);
    XtAddCallback (eyctxt[i], XmNvalueChangedCallback, EYCTxt_CB, (XtPointer) NULL);
    }

  for (i = 0; i < 3; i++)
    {
    label = XmStringCreateLocalized (num_buttons[i]);
    sprintf (wname, "EYCPB%d", i);
    eycpb[i] = XtVaCreateManagedWidget (wname,
      xmPushButtonGadgetClass, numform,
      XmNlabelString, label,
      XmNtopPosition, 750,
      XmNtopAttachment, XmATTACH_POSITION,
      XmNleftPosition, 200 * i + 100,
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);
    XtAddCallback (eycpb[i], XmNactivateCallback, EYCPB_CB, (XtPointer) i);
    }

  eform = XtVaCreateWidget ("EYCNumForm",
    xmFormWidgetClass, formdg,
    XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
    XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
    XmNtopOffset, 0,
    XmNtopAttachment, XmATTACH_FORM,
    XmNbottomOffset, 0,
    XmNbottomAttachment, XmATTACH_FORM,
    XmNleftOffset, 0,
    XmNleftAttachment, XmATTACH_FORM,
    XmNrightOffset, 0,
    XmNrightAttachment, XmATTACH_FORM,
    XmNfractionBase,    800,
    NULL);

  for (i = 0; i < 4; i++)
    {
    label = XmStringCreateLocalized (ease_questions[i]);
    sprintf (wname, "ELbl%d", i);
    elbl[i] = XtVaCreateManagedWidget (wname,
      xmLabelWidgetClass, eform,
      XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
      XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
      XmNlabelString, label,
      XmNtopOffset, 0,
      XmNtopAttachment, i == 0 ? XmATTACH_FORM : XmATTACH_WIDGET,
      XmNtopWidget, i == 0 ? NULL : emenu[i - 1],
      XmNleftPosition, 10,
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);

    for (nchoices = 0; nchoices < 5 && ease_choices[i][nchoices][0] != '\0'; nchoices++);
    for (j = 0; j < nchoices; j++) choice_lbl[j] = XmStringCreateLocalized (ease_choices[i][j]);
    sprintf (wname, "_easepulldown%d", i);
    edummy[i] = XmVaCreateSimplePulldownMenu (eform, wname, 0, NULL, XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR), NULL);

    title = XmStringCreateLocalized ("");
    sprintf (wname, "_easemenu%d", i);
    switch (nchoices)
      {
    case 3:
      emenu[i] = XmVaCreateSimpleOptionMenu (eform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, edummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, elbl[i],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
    case 4:
      emenu[i] = XmVaCreateSimpleOptionMenu (eform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, edummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[3], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, elbl[i],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
    case 5:
      emenu[i] = XmVaCreateSimpleOptionMenu (eform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, edummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[3], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[4], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, elbl[i],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
      }
    for (j = 0; j < nchoices; j++) XmStringFree (choice_lbl[j]);
    XmStringFree (title);
    XtManageChild (emenu[i]);
    }

  for (i = 0; i < 2; i++)
    {
    label = XmStringCreateLocalized (eyc_buttons[i]);
    sprintf (wname, "EPB%d", i);
    epb[i] = XtVaCreateManagedWidget (wname,
      xmPushButtonGadgetClass, eform,
      XmNlabelString, label,
      XmNtopPosition, 750,
      XmNtopAttachment, XmATTACH_POSITION,
      XmNleftPosition, 275 * (i + 1),
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);
    XtAddCallback (epb[i], XmNactivateCallback, EYCPB_CB, (XtPointer) (i + 3));
    }

  yform = XtVaCreateWidget ("EYCNumForm",
    xmFormWidgetClass, formdg,
    XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
    XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
    XmNtopOffset, 0,
    XmNtopAttachment, XmATTACH_FORM,
    XmNbottomOffset, 0,
    XmNbottomAttachment, XmATTACH_FORM,
    XmNleftOffset, 0,
    XmNleftAttachment, XmATTACH_FORM,
    XmNrightOffset, 0,
    XmNrightAttachment, XmATTACH_FORM,
    XmNfractionBase,    800,
    NULL);

  for (i = 0; i < 11; i++)
    {
    label = XmStringCreateLocalized (yield_question[i]);
    sprintf (wname, "YLbl%d", i);
    ylbl[i] = XtVaCreateManagedWidget (wname,
      xmLabelWidgetClass, yform,
      XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
      XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
      XmNlabelString, label,
      XmNtopOffset, 0,
      XmNtopAttachment, i == 0 ? XmATTACH_FORM : XmATTACH_WIDGET,
      XmNtopWidget, i == 0 ? NULL : ylbl[i - 1],
      XmNleftPosition, 10,
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);
    }

  ytxt = XtVaCreateManagedWidget ("YTxt",
    xmTextFieldWidgetClass, yform,
    XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
    XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
    XmNvalue, eycval[1],
    XmNtopOffset, 0,
    XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET,
    XmNtopWidget, ylbl[10],
    XmNleftOffset, 0,
    XmNleftAttachment, XmATTACH_WIDGET,
    XmNleftWidget, ylbl[10],
    NULL);
  XtAddCallback (ytxt, XmNvalueChangedCallback, EYCTxt_CB, (XtPointer) NULL);

  for (i = 0; i < 2; i++)
    {
    label = XmStringCreateLocalized (eyc_buttons[i]);
    sprintf (wname, "EPB%d", i);
    ypb[i] = XtVaCreateManagedWidget (wname,
      xmPushButtonGadgetClass, yform,
      XmNlabelString, label,
      XmNtopPosition, 750,
      XmNtopAttachment, XmATTACH_POSITION,
      XmNleftPosition, 275 * (i + 1),
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);
    XtAddCallback (ypb[i], XmNactivateCallback, EYCPB_CB, (XtPointer) (i + 5));
    }

  cform = XtVaCreateWidget ("EYCNumForm",
    xmFormWidgetClass, formdg,
    XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
    XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
    XmNtopOffset, 0,
    XmNtopAttachment, XmATTACH_FORM,
    XmNbottomOffset, 0,
    XmNbottomAttachment, XmATTACH_FORM,
    XmNleftOffset, 0,
    XmNleftAttachment, XmATTACH_FORM,
    XmNrightOffset, 0,
    XmNrightAttachment, XmATTACH_FORM,
    XmNfractionBase,    800,
    NULL);

  for (i = 0; i < 4; i++)
    {
    for (nlines = 0; nlines < 2 && conf_questions[i][nlines][0] != '\0'; nlines++);
    for (j = 0; j < nlines; j++)
      {
      label = XmStringCreateLocalized (conf_questions[i][j]);
      sprintf (wname, "CLbl%d_%d", i, j);
      clbl[i][j] = XtVaCreateManagedWidget (wname,
        xmLabelWidgetClass, cform,
        XmNbackground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get (&GSynAppR, SAR_CLRI_BLACK),
        XmNlabelString, label,
        XmNtopOffset, 0,
        XmNtopAttachment, i == 0 && j == 0 ? XmATTACH_FORM : XmATTACH_WIDGET,
        XmNtopWidget, j == 0 ? (i == 0 ? NULL : cmenu[i - 1]) : clbl[i][j - 1],
        XmNleftPosition, 10,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      XmStringFree (label);
      }

    for (nchoices = 0; nchoices < 5 && conf_choices[i][nchoices][0] != '\0'; nchoices++);
    for (j = 0; j < nchoices; j++) choice_lbl[j] = XmStringCreateLocalized (conf_choices[i][j]);
    sprintf (wname, "_confpulldown%d", i);
    cdummy[i] = XmVaCreateSimplePulldownMenu (cform, wname, 0, NULL, XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR), NULL);

    title = XmStringCreateLocalized ("");
    sprintf (wname, "_confmenu%d", i);
    switch (nchoices)
      {
    case 3:
      cmenu[i] = XmVaCreateSimpleOptionMenu (cform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, cdummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, clbl[i][nlines - 1],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
    case 4:
      cmenu[i] = XmVaCreateSimpleOptionMenu (cform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, cdummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[3], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, clbl[i][nlines - 1],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
    case 5:
      cmenu[i] = XmVaCreateSimpleOptionMenu (cform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, cdummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[3], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[4], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, clbl[i][nlines - 1],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
/*
    case 6:
      cmenu[i] = XmVaCreateSimpleOptionMenu (cform, wname, title, '\0', 0, EYCOpt_CB,
        XmNsubMenuId, cdummy[i],
        XmNbuttonFontList, SynAppR_FontList_Get (&GSynAppR),
        XmNbackground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_WHITE),
        XmNforeground, SynAppR_IthClrPx_Get(&GSynAppR, SAR_CLRI_BLACK),
        XmVaPUSHBUTTON, choice_lbl[0], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[1], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[2], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[3], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[4], '\0', NULL, NULL,
        XmVaPUSHBUTTON, choice_lbl[5], '\0', NULL, NULL,
        XmNtopOffset, 0,
        XmNtopAttachment, XmATTACH_WIDGET,
        XmNtopWidget, clbl[i][nlines - 1],
        XmNleftPosition, 20,
        XmNleftAttachment, XmATTACH_POSITION,
        NULL);
      break;
*/
      }
    for (j = 0; j < nchoices; j++) XmStringFree (choice_lbl[j]);
    XmStringFree (title);
    XtManageChild (cmenu[i]);
    }

  for (i = 0; i < 2; i++)
    {
    label = XmStringCreateLocalized (eyc_buttons[i]);
    sprintf (wname, "EPB%d", i);
    cpb[i] = XtVaCreateManagedWidget (wname,
      xmPushButtonGadgetClass, cform,
      XmNlabelString, label,
      XmNtopPosition, 750,
      XmNtopAttachment, XmATTACH_POSITION,
      XmNleftPosition, 275 * (i + 1),
      XmNleftAttachment, XmATTACH_POSITION,
      NULL);
    XmStringFree (label);
    XtAddCallback (cpb[i], XmNactivateCallback, EYCPB_CB, (XtPointer) (i + 7));
    }
}

void EYC_Open (int inp_ease, int inp_yld, int inp_conf, void (*return_function)(int, int, int))
{
  char eycval[3][5];
  int i;
  XmString title;

  ease = inp_ease;
  yield = inp_yld;
  conf = inp_conf;
  ret_func = return_function;

  sprintf (eycval[0], "%d", ease);
  sprintf (eycval[1], "%d", yield);
  sprintf (eycval[2], "%d", conf);

  for (i = 0; i < 3; i++)
    XtVaSetValues (eyctxt[i],
      XmNvalue, eycval[i],
      NULL);

  XtVaSetValues (ytxt,
    XmNvalue, eycval[1],
    NULL);

  title = XmStringCreateLocalized ("Ease, Yield, Confidence");
  XtVaSetValues (formdg,
    XmNdialogTitle, title,
    NULL);
  XmStringFree (title);

  XtUnmanageChild (eform);
  XtUnmanageChild (yform);
  XtUnmanageChild (cform);
  XtManageChild (numform);
  XtManageChild (formdg);
}

int adj_e (char *ans)
{
  int i, j, k, e;

  for (i = 0, e = 100; i < 4; i++)
    {
    for (j = 0, k = -1; j < 5 && k < 0; j++)
      if (ans[i] == ease_answers[i][j]) k = j;
    e -= 6 * k;
    }
  i = e % 5;
  if (i < 3) e -= i;
  else e += 5 - i;

  return (e);
}

int adj_c (char *ans)
{
  int i, j, k, c;

  for (i = 0, c = 100; i < 4; i++)
    {
    for (j = 0, k = -1; j < 5 && k < 0; j++)
      if (ans[i] == conf_answers[i][j]) k = j;
    c -= 6 * k;
    }
  i = c % 5;
  if (i < 3) c -= i;
  else c += 5 - i;

  return (c);
}

void EYCTxt_CB (Widget w, XtPointer client_data, XtPointer call_data)
{
  char *lcl_str, str[128];
  int len, i;
  static Boolean_t internal_change = FALSE;

  if (internal_change) return; /* ignore callback due to field truncation */

  lcl_str = XmTextGetString(w);
  strcpy (str, lcl_str);
  XtFree (lcl_str);

  len = strlen (str);

  if (len > 3)
    {
    str[len - 1] = '\0';
    internal_change = TRUE;
    XmTextReplace (w,0,len,str);
    len--;
    internal_change = FALSE;
    XBell (XtDisplay (w), 10);
    }

  if (len == 3 && strcmp (str, "100"))
    {
    str[len - 1] = '\0';
    internal_change = TRUE;
    XmTextReplace (w,0,len,str);
    len--;
    internal_change = FALSE;
    XBell (XtDisplay (w), 10);
    }

  for (i = 0; i < len; i++) if (str[i] < '0' || str[i] > '9')
    {
    strcpy (str + i, str + i + 1);
    internal_change = TRUE;
    XmTextReplace (w,0,len,str);
    len--;
    internal_change = FALSE;
    XBell (XtDisplay (w), 10);
    }
}

void EYCOpt_CB (Widget w, XtPointer client_data, XtPointer call_data)
{
  char *wname;
  int which, sel;

  sel = (int) client_data;
  wname = XtName (XtParent (w));
  which = wname[strlen(wname) - 1] - '0';

  if (strstr (wname, "ease")) esel[which] = sel;
  else csel[which] = sel;
}

void EYCPB_CB (Widget w, XtPointer client_data, XtPointer call_data)
{
  char *ts, choices[4], eycval[3][5];
  int i;
  XmString title;

  switch ((int) client_data)
    {
  case 0: /* Exit and Save */
    XtVaGetValues (eyctxt[0],
      XmNvalue, &ts,
      NULL);
    ease = atoi (ts);
    XtVaGetValues (eyctxt[1],
      XmNvalue, &ts,
      NULL);
    yield = atoi (ts);
    XtVaGetValues (eyctxt[2],
      XmNvalue, &ts,
      NULL);
    conf = atoi (ts);
    XtUnmanageChild (formdg);
    (*ret_func) (ease, yield, conf);
    break;
  case 1: /* Stepwise */
    XtUnmanageChild (numform);
    XtManageChild (eform);
    title = XmStringCreateLocalized ("Initial Ease");
    XtVaSetValues (formdg,
      XmNdialogTitle, title,
      NULL);
    XmStringFree (title);
    break;
  case 2: /* Quit and Cancel */
  case 4:
  case 6:
  case 8:
    XtUnmanageChild (formdg);
    break;
  case 3: /* Submit and Continue (ease) */
    for (i=0; i<4; i++) choices[i] = ease_choices[i][esel[i]][0];
    ease = adj_e (choices);
    XtUnmanageChild (eform);
    XtManageChild (yform);
    title = XmStringCreateLocalized ("Initial Yield");
    XtVaSetValues (formdg,
      XmNdialogTitle, title,
      NULL);
    XmStringFree (title);
    break;
  case 5: /* Submit and Continue (yld) */
    XtVaGetValues (ytxt,
      XmNvalue, &ts,
      NULL);
    yield = atoi (ts);
    XtUnmanageChild (yform);
    XtManageChild (cform);
    title = XmStringCreateLocalized ("Initial Confidence");
    XtVaSetValues (formdg,
      XmNdialogTitle, title,
      NULL);
    XmStringFree (title);
    break;
  case 7: /* Submit and Continue (conf) */
    for (i=0; i<4; i++) choices[i] = conf_choices[i][csel[i]][0];
    conf = adj_c (choices);
    XtUnmanageChild (cform);
    sprintf (eycval[0], "%d", ease);
    sprintf (eycval[1], "%d", yield);
    sprintf (eycval[2], "%d", conf);
    for (i = 0; i < 3; i++)
      XtVaSetValues (eyctxt[i],
        XmNvalue, eycval[i],
        NULL);
    XtManageChild (numform);
    title = XmStringCreateLocalized ("Ease, Yield, Confidence");
    XtVaSetValues (formdg,
      XmNdialogTitle, title,
      NULL);
    XmStringFree (title);
    break;
    }
}
